version: 2
before:
  hooks:
    - go mod tidy
    - sh -c "curl https://github.com/porjo.gpg | gpg --import"
    - git verify-tag {{.Version}}
builds:
  - env:
    - CGO_ENABLED=0
    main: ./cmd/youtubeuploader
    ldflags:
      - -X main.appVersion={{.Version}}
    targets:
      - linux_amd64
      - linux_arm64
      - linux_arm_6
      - linux_arm_7
      - windows_amd64
      - darwin_amd64
      - darwin_arm64
      - freebsd_amd64
      - openbsd_amd64
archives:
  -
    name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
